services:
  database:
    image: postgres
    container_name: chowkidaar
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chowkidaar
    volumes:
      - psqldata:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  psqldata: